MOSIP-37357 Corrected readme
mosip/mosip-ref-impl pull request #1025
Opened 2024-11-08 06:27 UTC by kameshsr

2024-11-08 15:14 UTC, ashok-ksharma requested changes

2024-11-08 15:14 UTC, ashok-ksharma commented on registration-processor/registration-processor-external-integration-service/README.md
> +   ```
We are not keeping it here. This service is not even using the auth adapter in the DockerFile.

2024-11-08 15:14 UTC, ashok-ksharma commented on registration-processor/registration-processor-external-integration-service/README.md
> +API documentation is available [here](https://mosip.github.io/documentation/).
This link is not working. Link which will be provided should contains the API details for this service otherwise remove this section.

2024-11-08 15:14 UTC, ashok-ksharma commented on registration-processor/registration-processor-external-stage/README.md
> +This is to maintain compatibility with existing ANT-style path patterns.
This can be removed.

2024-11-08 15:14 UTC, ashok-ksharma commented on registration-processor/registration-processor-external-stage/README.md
> +[Configuration-Registration](https://github.com/mosip/mosip-config/blob/develop/registration-default.properties) defined here.
Are we sure it is using the pre-reg configuration. If not please change the same and point to the right config. Please follow the same for config as commented for above services.

2024-11-08 15:14 UTC, ashok-ksharma commented on registration-processor/registration-processor-external-stage/README.md
> +API documentation is available [here](https://mosip.github.io/documentation/).
Does this link contains the API details for this. If not we can remove this link.

2024-11-08 15:14 UTC, ashok-ksharma commented on registration-processor/registration-processor-external-stage/README.md
> +This project is licensed under the terms of [Mozilla Public License 2.0](LICENSE).
Link is not working.

2024-11-11 04:48 UTC, kameshsr commented on pre-registration-booking-service/README.md
> +Refer to [SQL scripts](https://github.com/mosip/pre-registration/tree/develop/db_scripts).
https://github.com/mosip/pre-registration/tree/master/db_scripts Refereed to master is it fine?

2024-11-11 04:48 UTC, kameshsr commented on pre-registration-booking-service/README.md
> +This is to maintain compatibility with existing ANT-style path patterns.
Removed

2024-11-11 04:51 UTC, kameshsr commented on pre-registration-booking-service/README.md
> +Refer [Module Configuration](https://docs.mosip.io/1.2.0/modules/module-configuration) for location of these files.
Done

2024-11-11 04:51 UTC, kameshsr commented on registration-processor/registration-processor-external-integration-service/README.md
> +This is to maintain compatibility with existing ANT-style path patterns.
removed

2024-11-11 04:52 UTC, kameshsr commented on registration-processor/registration-processor-external-integration-service/README.md
> +## Overview
done.

2024-11-11 04:54 UTC, kameshsr commented on registration-processor/registration-processor-external-integration-service/README.md
> +   ```
Removed.

2024-11-11 04:54 UTC, kameshsr commented on registration-processor/registration-processor-external-integration-service/README.md
> +[Configuration-Registration](https://github.com/mosip/mosip-config/blob/develop/registration-default.properties) defined here.
Done.

2024-11-11 04:55 UTC, kameshsr commented on registration-processor/registration-processor-external-stage/README.md
> +This is to maintain compatibility with existing ANT-style path patterns.
Removed

2024-11-11 04:58 UTC, kameshsr commented on registration-processor/registration-processor-external-stage/README.md
> +[Configuration-Registration](https://github.com/mosip/mosip-config/blob/develop/registration-default.properties) defined here.
Done.

2024-11-11 04:59 UTC, kameshsr commented on registration-processor/registration-processor-external-integration-service/README.md
> +API documentation is available [here](https://mosip.github.io/documentation/).
Done.

2024-11-11 05:00 UTC, kameshsr commented on registration-processor/registration-processor-external-stage/README.md
> +API documentation is available [here](https://mosip.github.io/documentation/).
Done.

2024-11-11 05:00 UTC, kameshsr commented on registration-processor/registration-processor-external-stage/README.md
> +This project is licensed under the terms of [Mozilla Public License 2.0](LICENSE).
Done.

2024-11-11 11:41 UTC, ashok-ksharma requested changes

2024-11-11 11:41 UTC, ashok-ksharma commented on pre-registration-booking-service/README.md
> +Refer to the required released tagged version [Module Configuration](https://docs.mosip.io/1.2.0/modules/module-configuration) for location of these files.
1. These are coming in the single line only. Can we format it correctly.
2. Is this correct "Need to run the config-server along with the files mentioned above in order to run the **master-data service**."?

2024-11-11 11:41 UTC, ashok-ksharma commented on pre-registration-booking-service/README.md
> +This project is licensed under the terms of [Mozilla Public License 2.0](LICENSE).
Link is not working.

2024-11-11 11:41 UTC, ashok-ksharma commented on pre-registration-booking-service/README.md
> +   </dependency>
We are using kernel-ref-idobjectvalidator.jar library as well. Can we add this also:
https://github.com/kameshsr/mosip-ref-impl/blob/MOSIP-37357/pre-registration-booking-service/Dockerfile#L95C130-L95C162

2024-11-11 11:41 UTC, ashok-ksharma commented on pre-registration-booking-service/README.md
> +API documentation is available [here](https://mosip.github.io/documentation/1.2.0/pre-registration-booking-service.html).
Can we add below link to be compatible with other repos:
https://mosip.github.io/documentation/

2024-11-11 11:41 UTC, ashok-ksharma commented on registration-processor/registration-processor-external-integration-service/README.md
> +Need to run the config-server along with the files mentioned above in order to run the master-data service.
1. It is coming in single line. Can we format it correctly.
2. Link should point to master.
3. Here it should point to registration-processor file not registration. Please check below:https://mosip.github.io/documentation.
4. Is this line correct: Need to run the config-server along with the files mentioned above in order to run the **master-data service.**?

2024-11-11 11:41 UTC, ashok-ksharma commented on registration-processor/registration-processor-external-integration-service/README.md
> +API documentation is available [here](https://mosip.github.io/documentation/1.2.0/registration-processor-external-integration-service.html).
Can we add below link to be compatible with other repos:
https://mosip.github.io/documentation/

2024-11-11 11:41 UTC, ashok-ksharma commented on registration-processor/registration-processor-external-integration-service/README.md
> +This project is licensed under the terms of [Mozilla Public License 2.0](LICENSE).
Link not working.

2024-11-11 11:53 UTC, kameshsr commented on pre-registration-booking-service/README.md
> +Refer to the required released tagged version [Module Configuration](https://docs.mosip.io/1.2.0/modules/module-configuration) for location of these files.
corrected.

2024-11-11 11:54 UTC, kameshsr commented on pre-registration-booking-service/README.md
> +   </dependency>
Done

2024-11-11 11:55 UTC, kameshsr commented on pre-registration-booking-service/README.md
> +API documentation is available [here](https://mosip.github.io/documentation/1.2.0/pre-registration-booking-service.html).
done.

2024-11-11 11:59 UTC, kameshsr commented on pre-registration-booking-service/README.md
> +This project is licensed under the terms of [Mozilla Public License 2.0](LICENSE).
Fixed

2024-11-11 12:00 UTC, kameshsr commented on registration-processor/registration-processor-external-integration-service/README.md
> +API documentation is available [here](https://mosip.github.io/documentation/1.2.0/registration-processor-external-integration-service.html).
corrected

2024-11-11 12:00 UTC, kameshsr commented on registration-processor/registration-processor-external-integration-service/README.md
> +This project is licensed under the terms of [Mozilla Public License 2.0](LICENSE).
corrected

2024-11-11 12:00 UTC, kameshsr commented on registration-processor/registration-processor-external-stage/README.md
> +This project is licensed under the terms of [Mozilla Public License 2.0](LICENSE).
corrected

2024-11-11 12:06 UTC, kameshsr commented on registration-processor/registration-processor-external-integration-service/README.md
> +Need to run the config-server along with the files mentioned above in order to run the master-data service.
corrected

2024-11-11 12:06 UTC, kameshsr commented on registration-processor/registration-processor-external-stage/README.md
> +Need to run the config-server along with the files mentioned above in order to run the master-data service.
corrected

2024-11-12 08:18 UTC, ashok-ksharma approved these changes

2024-11-12 12:05 UTC, ckm007 approved these changes

2024-11-13 05:10 UTC, merged