MOSIP- 13633 added reg-proc external stage and service
mosip/mosip-ref-impl pull request #429
Opened 2021-04-29 07:28 UTC by neosoftSatish

2021-04-29 09:49 UTC, vishwa-vyom requested changes

2021-04-29 09:49 UTC, vishwa-vyom commented on registration-processor-external-stage/src/main/java/io/mosip/registrationprocessor/externalstage/stage/ExternalStage.java
> +				this.postUrl(vertx, MessageBusAddress.EXTERNAL_STAGE_BUS_IN, MessageBusAddress.EXTERNAL_STAGE_BUS_OUT));
Please change this.postUrl(vertx, to this.postUrl(getVertx(),

2021-04-29 09:49 UTC, vishwa-vyom commented on registration-processor-external-integration-service/README.md
> +```
This service does not need any properties from the config server ?

2021-04-29 09:49 UTC, vishwa-vyom commented on .github/workflows/push_trigger.yml
> +      SERVICE_LOCATION: registration-processor/pre-processor/registration-processor-external-stage
This location is not correct

2021-04-29 09:49 UTC, vishwa-vyom commented on .github/workflows/push_trigger.yml
> +    runs-on: ubuntu-latest
This section has to be like the other in this yml file, I will anyway ask Mono to check these sections once

2021-04-29 09:49 UTC, vishwa-vyom commented on .github/workflows/push_trigger.yml
> +  docker-registration-processor-external-stage:
Create a folder called registration-processor and keep both the projects inside that

2021-04-29 10:06 UTC, neosoftSatish commented on registration-processor-external-integration-service/README.md
> +```
checked all classes, I have not seen any properties needed in this project.

2021-04-29 12:16 UTC, vishwa-vyom reviewed
All the review comments are taken care, requesting @MonobikashDas to review the push_trigger.yml and release_trigger.yml file alone and then we are good to merge

2021-04-29 12:56 UTC, MonobikashDas commented on .github/workflows/push_trigger.yml
> +  docker-registration-processor-external-stage:
Hi @neosoftSatish ,
This is not correct. You are not building code. Directly building image.
Correct steps -
1. setup env/gpg key
2. Build with Maven
3. then comes - build image (which u are doing directly here)
4. push image

CC @vishwa-vyom

2021-04-29 12:57 UTC, MonobikashDas requested changes
follow example of "build-pre-registration-booking-service" and do the changes for registration-processor-external-stage and external-service

2021-05-06 14:10 UTC, MonobikashDas approved these changes

2021-05-06 14:10 UTC, merged