Mosip 32461 develop java21
mosip/mosip-ref-impl pull request #985
Opened 2024-04-19 08:40 UTC by sowmya695

2024-04-22 05:20 UTC, LoganathanSekar7627 requested changes

2024-04-22 05:20 UTC, LoganathanSekar7627 commented on kernel/kernel-ref-idobjectvalidator/pom.xml
> +		<kernel-logger-logback.version>1.2.1-java21-SNAPSHOT</kernel-logger-logback.version>
Add 
<maven.compiler.source>21</maven.compiler.source>
		<maven.compiler.target>21</maven.compiler.target>

2024-04-22 05:22 UTC, sowmya695 commented on kernel/kernel-ref-idobjectvalidator/pom.xml
> +		<kernel-logger-logback.version>1.2.1-java21-SNAPSHOT</kernel-logger-logback.version>
It is present in parent kernel-ref-parent,so i have removed here.Whether i need to add again?

2024-04-22 05:25 UTC, LoganathanSekar7627 approved these changes

2024-04-23 04:36 UTC, ckm007 approved these changes

2024-04-23 04:37 UTC, merged