Develop java21 1
mosip/mosip-ref-impl pull request #986
Opened 2024-04-22 08:13 UTC by Khuddusshariff0022

2024-04-22 08:50 UTC, sowmya695 commented on cache-provider-redis/pom.xml
> +        <jedis.version>2.9.0</jedis.version>
spell check need to correct to redis

2024-04-22 08:54 UTC, sowmya695 requested changes
Please change for @master to @master-java21 in push-trigger.yml for only cache-provider-hazelcast

2024-04-22 09:58 UTC, sowmya695 approved these changes

2024-04-23 07:23 UTC, ckm007 approved these changes

2024-04-23 07:33 UTC, merged